name: shonenx

description: >
  ðŸš€ ShonenX is a blazing-fast, modern, and user-friendly anime streaming app built with Flutter.
  Stream your favorite anime, keep track of your watch progress, and explore trending shows â€”
  all in one place. Built with â¤ï¸ by Darkx-dev.

publish_to: "none"

version: 1.7.5+12

environment:
  sdk: ">=3.5.1"

dependencies:
  awesome_snackbar_content: ^0.1.7
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  collection: ^1.19.1
  connectivity_plus: ^6.1.5
  crypto: ^3.0.6
  d4rt: ^0.1.9
  desktop_webview_window: ^0.2.3
  device_info_plus: ^11.2.1
  dio: ^5.9.0
  dynamic_color: 1.7.0
  encrypt: ^5.0.3
  file_picker: ^10.3.10
  flex_color_picker: ^3.7.2
  flex_color_scheme: ^8.3.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^20.0.0
  flutter_markdown: ^0.7.7+1
  flutter_qjs:
    git:
      url: https://github.com/kodjodevf/flutter_qjs.git
      ref: main
  flutter_riverpod: ^3.0.1
  flutter_secure_storage:
    git:
      url: https://github.com/juliansteenbakker/flutter_secure_storage.git
      ref: master
      path: flutter_secure_storage
  flutter_staggered_animations: ^1.1.1
  flutter_web_auth_2: ^4.1.0
  glass_kit: ^4.0.2
  go_router: ^14.7.1
  google_fonts: ^6.2.1
  graphql: ^5.2.3
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.1.0
  html: ^0.15.5
  http: ^1.3.0
  http_interceptor: ^2.0.0
  iconsax: ^0.0.8
  image: ^4.5.3
  install_plugin: ^2.1.0
  intl: ^0.20.2
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  js_packer: ^0.0.5
  logger: ^2.5.0
  media_kit: ^1.2.6
  media_kit_libs_video: ^1.0.7
  media_kit_video: ^2.0.1
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  pseudom: ^1.0.1
  rename: ^3.0.2
  riverpod_annotation: ^3.0.1
  screenshot: ^3.0.0
  url_launcher: ^6.3.1
  window_manager: ^0.4.3
  workmanager: ^0.9.0+3
  xpath_selector_html_parser: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.8.1
  riverpod_generator: ^3.0.0
  isar_community_generator: ^3.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon-modified-2.png

flutter_launcher_icons:
  android: true
  image_path_android: "assets/icons/app_icon-modified-2.png"
  windows:
    generate: true
    image_path: "assets/icons/app_icon-modified-2.png"

inno_bundle:
  id: 0516d984-72bf-47d4-bfbc-b2b8fd563479
  publisher: Roshan Kumar
  name: ShonenX
  url: https://github.com/roshancodespace/ShonenX
  support_url: https://github.com/roshancodespace/ShonenX/issues
  updates_url: https://github.com/roshancodespace/ShonenX/releases
  languages:
    - english
  admin: false