name: shonenx

description: >
  ðŸš€ ShonenX is a blazing-fast, modern, and user-friendly anime streaming app built with Flutter.
  Stream your favorite anime, keep track of your watch progress, and explore trending shows â€”
  all in one place. Built with â¤ï¸ by Darkx-dev.

publish_to: "none"

version: 1.7.6+12

environment:
  sdk: ">=3.8.1"

dependencies:
  dartotsu_extension_bridge:
    path: packages/dartotsu_extension_bridge
  awesome_snackbar_content: ^0.1.7
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  collection: ^1.19.1
  connectivity_plus: ^6.1.5
  commentum_client:
    git: 
      url: https://github.com/commentum/commentum_flutter.git
      ref: main
      path: ./
  # commentum_client:
  #   path: packages/commentum_client

  device_info_plus: ^11.2.1
  dynamic_color: 1.7.0
  encrypt: ^5.0.3
  file_picker: ^10.3.10
  flex_color_picker: ^3.7.2
  flex_color_scheme: ^8.3.1
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_local_notifications: ^20.0.0
  flutter_markdown: ^0.7.7+1
  flutter_riverpod: ^3.0.1
  flutter_secure_storage:
    git:
      url: https://github.com/juliansteenbakker/flutter_secure_storage.git
      ref: master
      path: flutter_secure_storage
  flutter_inappwebview:
    git:
      url: https://github.com/roshancodespace/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview
  flutter_volume_controller: ^1.3.4
  flutter_web_auth_2: ^5.0.1
  # flutter_web_auth_2:
  #   git: 
  #     url: https://github.com/aayush2622/flutter_web_auth.git
  #     ref: master
  #     path: flutter_web_auth_2
  go_router: ^17.1.0
  google_fonts: ^6.2.1
  graphql: ^5.2.3
  highlight: ^0.7.0
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.1.0
  html: ^0.15.5
  http: ^1.3.0
  http_interceptor: ^2.0.0
  iconsax: ^0.0.8
  image: ^4.5.3
  install_plugin: ^2.1.0
  intl: ^0.20.2
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  js_packer: ^0.0.5
  logger: ^2.5.0
  media_kit:
    git:
      url: https://github.com/Schnitzel5/media-kit.git
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/Schnitzel5/media-kit.git
      path: media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/Schnitzel5/media-kit.git
      path: libs/universal/media_kit_libs_video
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  pseudom: ^1.0.1
  rename: ^3.0.2
  riverpod_annotation: ^3.0.1
  screen_brightness: ^2.1.7
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.1
  window_manager: ^0.4.3
  workmanager: ^0.9.0+3
  xpath_selector_html_parser: ^3.0.1
  get: ^4.7.3
  timeago: ^3.7.1

dependency_overrides:
  flutter_inappwebview:
    git:
      url: https://github.com/roshancodespace/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.8.1
  riverpod_generator: ^3.0.0
  isar_community_generator: ^3.3.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon-modified-2.png

flutter_launcher_icons:
  android: true
  image_path_android: "assets/icons/app_icon-modified-2.png"
  windows:
    generate: true
    image_path: "assets/icons/app_icon-modified-2.png"

inno_bundle:
  id: 0516d984-72bf-47d4-bfbc-b2b8fd563479
  publisher: Roshan Kumar
  name: ShonenX
  url: https://github.com/roshancodespace/ShonenX
  support_url: https://github.com/roshancodespace/ShonenX/issues
  updates_url: https://github.com/roshancodespace/ShonenX/releases
  languages:
    - english
  admin: false
